env: "local" # local, dev, prod
weather_api:
  key: YOUR_WEATHER_API_KEY
  base_url: "http://api.weatherapi.com/v1/current.json"
telegram_bot:
  telegram_bot_token: YOUR_TELEGRAM_BOT_TOKEN
gigachat: 
  api_key:  YOUR_GIGACHAT_API_KEY
  base_url: "https://gigachat.devices.sberbank.ru/api/v1/chat/completions"
